minify:
  disableXML: true
  minifyOutput: true

buildDrafts: false
buildFuture: false

params:
  env: production
  comments: true
  services:
    umami_analytics:
      id: "98b882e2-1760-4639-bd20-eee629d534bd"
      script_url: https://umami.culturegremlin.club/script.js
